emit:
  - "@azure-tools/typespec-aaz"
options:
  "@azure-tools/typespec-aaz":
    api-version: "2024-04-01"
    operation: "get-resources-operations"
    resources:
      - "/subscriptions/{}/resourcegroups/{}/providers/microsoft.azuresphere/catalogs/{}/products/{}/devicegroups/{}/devices"
      - "/subscriptions/{}/resourcegroups/{}/providers/microsoft.azuresphere/catalogs/{}/products/{}/devicegroups/{}/devices/{}"
  "@azure-tools/typespec-autorest":
    omit-unreachable-types: true
    emitter-output-dir: "{project-root}/.."
    azure-resource-provider-folder: "resource-manager"
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/azuresphere.json"
    examples-directory: "{project-root}/examples"
  "@azure-tools/cadl-python":
    "basic-setup-py": true
    "package-version": 3.0.0b6
    "package-name": azure-sphere
  "@azure-tools/cadl-csharp":
    save-inputs: false
    clear-output-folder: true
    namespace: Azure.Sphere
    model-namespace: false
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
